/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.orderdb;

import view.orderdb.CustomerPanel;
import control.DatabaseManager;

/**
 *
 * @author Paul
 */
public class OrderDashboard extends javax.swing.JPanel {

    private DatabaseManager dbm;

    /**
     * Creates new form OrderDashboard
     */
    public OrderDashboard(final DatabaseManager dbm) {
        this.dbm = dbm;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OrdersTabbedPane = new javax.swing.JTabbedPane();
        NewOrderPanel = new NewOrderPanel(dbm);
        ActiveOrderPanel = new OrderPanel("ACTIVE", dbm);
        ClosedOrderPanel = new OrderPanel("CLOSED", dbm);
        CustomersPanel = new CustomerPanel(dbm);
        ReportsPanel = new ReportsPanel(dbm);

        setMinimumSize(new java.awt.Dimension(1280, 720));
        setLayout(new java.awt.GridLayout(1, 0));

        OrdersTabbedPane.addTab("New Order", NewOrderPanel);
        OrdersTabbedPane.addTab("Active Orders", ActiveOrderPanel);
        OrdersTabbedPane.addTab("Closed Orders", ClosedOrderPanel);
        OrdersTabbedPane.addTab("Customer Management", CustomersPanel);
        OrdersTabbedPane.addTab("Reports", ReportsPanel);

        add(OrdersTabbedPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.orderdb.OrderPanel ActiveOrderPanel;
    private view.orderdb.OrderPanel ClosedOrderPanel;
    private view.orderdb.CustomerPanel CustomersPanel;
    private view.orderdb.NewOrderPanel NewOrderPanel;
    private javax.swing.JTabbedPane OrdersTabbedPane;
    private view.orderdb.ReportsPanel ReportsPanel;
    // End of variables declaration//GEN-END:variables
}
