package view.orderdb;

import control.DatabaseManager;

/**
 * A custom JPanel that can hold information related to customers and orders
 * @author Paul Schmidt
 */
public class OrderDashboard extends javax.swing.JPanel {

    /**
     * The DatabaseManager that holds the connection to the database
     */
    private DatabaseManager dbm;

    /**
     * Creates an OrderDashboard Panel with a connection to the database
     * @param dbm the DDatabaseManager with that holds the connection to the database
     */
    public OrderDashboard(final DatabaseManager dbm) {
        this.dbm = dbm;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OrdersTabbedPane = new javax.swing.JTabbedPane();
        NewOrderPanel = new NewOrderPanel(dbm);
        ActiveOrderPanel = new OrderPanel("ACTIVE", dbm);
        ClosedOrderPanel = new OrderPanel("CLOSED", dbm);
        CustomersPanel = new CustomerPanel(dbm);
        ReportsPanel = new ReportsPanel(dbm);

        setMinimumSize(new java.awt.Dimension(1280, 720));
        setLayout(new java.awt.GridLayout(1, 0));

        OrdersTabbedPane.addTab("New Order", NewOrderPanel);
        OrdersTabbedPane.addTab("Active Orders", ActiveOrderPanel);
        OrdersTabbedPane.addTab("Closed Orders", ClosedOrderPanel);
        OrdersTabbedPane.addTab("Customer Management", CustomersPanel);
        OrdersTabbedPane.addTab("Reports", ReportsPanel);

        add(OrdersTabbedPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.orderdb.OrderPanel ActiveOrderPanel;
    private view.orderdb.OrderPanel ClosedOrderPanel;
    private view.orderdb.CustomerPanel CustomersPanel;
    private view.orderdb.NewOrderPanel NewOrderPanel;
    private javax.swing.JTabbedPane OrdersTabbedPane;
    private view.orderdb.ReportsPanel ReportsPanel;
    // End of variables declaration//GEN-END:variables
}
