/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import control.DatabaseManager;
import java.sql.SQLException;
import javax.swing.JTable;

/**
 *
 * @author Paul
 */
public class CustomerPanel extends javax.swing.JPanel {
    private DatabaseManager dbm;
    /**
     * Creates new form CustomerManagmenetPanel
     */
    public CustomerPanel() {
        initComponents();
    }
    public CustomerPanel(final DatabaseManager dbm) {
        this.dbm = dbm;
        initComponents();
        generateCustomers();
    }
    private void generateCustomers() {
        JTable testTable = null;
        try {
            testTable = dbm.executeQueryGetTable("select * from customers;");
            testTable.setAutoCreateRowSorter(true);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        if (testTable != null) {
            addTable(testTable);
            System.out.println("CUSTOEMRS TABLE ADDED");
        } else {
            System.out.println("ISSUE CREATING CUSTOMERS TABLE");
        }
    }
    private void addTable(final JTable table) {
        CustomerManagementScrollPane.getViewport().remove(CustomersTable);
        CustomersTable = table;
        CustomerManagementScrollPane.getViewport().add(CustomersTable);
        revalidate();
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerManagementPanel = new javax.swing.JPanel();
        NewCustomerButton = new javax.swing.JButton();
        EditCustomerButton = new javax.swing.JButton();
        CustomerManagementScrollPane = new javax.swing.JScrollPane();
        CustomersTable = new javax.swing.JTable();

        NewCustomerButton.setText("New Customer");
        NewCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCustomerButtonActionPerformed(evt);
            }
        });

        EditCustomerButton.setText("Edit Selected");

        CustomersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CustomerID", "FirstName", "LastName", "Email", "Address", "Phone", "CustomerType", "LocationID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CustomerManagementScrollPane.setViewportView(CustomersTable);

        javax.swing.GroupLayout CustomerManagementPanelLayout = new javax.swing.GroupLayout(CustomerManagementPanel);
        CustomerManagementPanel.setLayout(CustomerManagementPanelLayout);
        CustomerManagementPanelLayout.setHorizontalGroup(
            CustomerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerManagementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomerManagementScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CustomerManagementPanelLayout.createSequentialGroup()
                        .addComponent(NewCustomerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditCustomerButton)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        CustomerManagementPanelLayout.setVerticalGroup(
            CustomerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerManagementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewCustomerButton)
                    .addComponent(EditCustomerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomerManagementScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CustomerManagementPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CustomerManagementPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NewCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCustomerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewCustomerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustomerManagementPanel;
    private javax.swing.JScrollPane CustomerManagementScrollPane;
    private javax.swing.JTable CustomersTable;
    private javax.swing.JButton EditCustomerButton;
    private javax.swing.JButton NewCustomerButton;
    // End of variables declaration//GEN-END:variables
}
