/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import control.DatabaseManager;

/**
 *
 * @author Paul
 */
public class LoginFrame extends javax.swing.JFrame {
    private MainFrame main;
    private LoginFrame thisFrame;
    private DatabaseManager dbm;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame(final String theme) {
        initComponents();
        dbm = new DatabaseManager();
        main = new MainFrame(theme, dbm);
        thisFrame = this;
    }
    private void goToOrder() {
        OrderDashboard od = new OrderDashboard(dbm);
        main.add(od);
        main.setVisible(true);
        thisFrame.dispose();
    }
    private void goToLogistics() {
        LogisticDashboard ld = new LogisticDashboard(dbm);
        main.add(ld);
        main.setVisible(true);
        thisFrame.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameLabel = new javax.swing.JLabel();
        ButtonsPanel = new javax.swing.JPanel();
        OrderFormButton = new javax.swing.JButton();
        LogisticsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(340, 450));
        setMinimumSize(new java.awt.Dimension(340, 450));
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        NameLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameLabel.setText("GSR Global");
        getContentPane().add(NameLabel);

        ButtonsPanel.setPreferredSize(new java.awt.Dimension(340, 225));

        OrderFormButton.setText("Order Dashboard");
        OrderFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderFormButtonActionPerformed(evt);
            }
        });

        LogisticsButton.setText("Logistics Dashboard");
        LogisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogisticsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonsPanelLayout = new javax.swing.GroupLayout(ButtonsPanel);
        ButtonsPanel.setLayout(ButtonsPanelLayout);
        ButtonsPanelLayout.setHorizontalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogisticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );
        ButtonsPanelLayout.setVerticalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(OrderFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LogisticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        getContentPane().add(ButtonsPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogisticsButtonActionPerformed
        thisFrame.goToLogistics();
    }//GEN-LAST:event_LogisticsButtonActionPerformed

    private void OrderFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderFormButtonActionPerformed
        thisFrame.goToOrder();
    }//GEN-LAST:event_OrderFormButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JButton LogisticsButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton OrderFormButton;
    // End of variables declaration//GEN-END:variables
}
