/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Paul
 */
public class OrderDashboard extends javax.swing.JPanel {

    /**
     * Creates new form OrderDashboard
     */
    public OrderDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OrdersTabbedPane = new javax.swing.JTabbedPane();
        NewOrderPanel = new javax.swing.JPanel();
        CustSelectLabel = new javax.swing.JLabel();
        CustomerComboBox = new javax.swing.JComboBox<>();
        FirstNameField = new javax.swing.JTextField();
        LastNameField = new javax.swing.JTextField();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        SearchForCustomerButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        CustInfoLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        CustFirstNameLabel = new javax.swing.JLabel();
        CustLastNameLabel = new javax.swing.JLabel();
        CustFirstName = new javax.swing.JLabel();
        CustLastName = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        CustEmail = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        CustPhone = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        StreetLabel = new javax.swing.JLabel();
        CustStreet = new javax.swing.JLabel();
        CityLabel = new javax.swing.JLabel();
        CustCity = new javax.swing.JLabel();
        StateLabel = new javax.swing.JLabel();
        CustState = new javax.swing.JLabel();
        ZipLabel = new javax.swing.JLabel();
        CustZip = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        OrderItemsLabel = new javax.swing.JLabel();
        DeleteItemButton = new javax.swing.JButton();
        EditItemButton = new javax.swing.JButton();
        AddItemButton = new javax.swing.JButton();
        SubmitOrderButton = new javax.swing.JButton();
        ItemsScrollPane = new javax.swing.JScrollPane();
        OrderItemsTable = new javax.swing.JTable();
        SubtotalLabel = new javax.swing.JLabel();
        OrderSubtotalLabel = new javax.swing.JLabel();
        ActiveOrdersPanel = new javax.swing.JPanel();
        ActiveOrdersScrollPane = new javax.swing.JScrollPane();
        AcitveOrdersTable = new javax.swing.JTable();
        ApplyFiltersActiveButton = new javax.swing.JButton();
        ResetFiltersActiveButton = new javax.swing.JButton();
        ClosedOrdersPanel = new javax.swing.JPanel();
        ClosedOrdersScrollPane = new javax.swing.JScrollPane();
        ClosedOrdersTable = new javax.swing.JTable();
        ApplyFiltersClosedButton = new javax.swing.JButton();
        ResetFiltersClosedButton = new javax.swing.JButton();
        CustomerManagementPanel = new javax.swing.JPanel();
        NewCustomerButton = new javax.swing.JButton();
        EditCustomerButton = new javax.swing.JButton();
        CustomerManagementScrollPane = new javax.swing.JScrollPane();
        CustomersTable = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1280, 720));
        setLayout(new java.awt.GridLayout(1, 0));

        CustSelectLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CustSelectLabel.setText("Customer Selection");

        CustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        FirstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameFieldActionPerformed(evt);
            }
        });

        LastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameFieldActionPerformed(evt);
            }
        });

        FirstNameLabel.setText("First Name");

        LastNameLabel.setText("Last Name");

        SearchForCustomerButton.setText("Search");

        CustInfoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CustInfoLabel.setText("Customer Info");

        CustFirstNameLabel.setText("First Name");

        CustLastNameLabel.setText("Last Name");

        CustFirstName.setText("(none selected)");

        CustLastName.setText("(none selected)");

        EmailLabel.setText("Email");

        CustEmail.setText("(none selected)");

        PhoneLabel.setText("Phone");

        CustPhone.setText("(###-###-####)");

        AddressLabel.setText("Address");

        StreetLabel.setText("Street");

        CustStreet.setText("(street address-----------------------)");

        CityLabel.setText("City");

        CustCity.setText("(city---------)");

        StateLabel.setText("State");

        CustState.setText("##");

        ZipLabel.setText("ZIP");

        CustZip.setText("#####");

        OrderItemsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        OrderItemsLabel.setText("Order Items");

        DeleteItemButton.setText("Delete Selected");
        DeleteItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteItemButtonActionPerformed(evt);
            }
        });

        EditItemButton.setText("Edit Selected");

        AddItemButton.setText("Add Item");
        AddItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemButtonActionPerformed(evt);
            }
        });

        SubmitOrderButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SubmitOrderButton.setText("Submit Order");
        SubmitOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitOrderButtonActionPerformed(evt);
            }
        });

        OrderItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ProductID", "ProductName", "UnitPrice", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ItemsScrollPane.setViewportView(OrderItemsTable);

        SubtotalLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SubtotalLabel.setText("Subtotal: $");

        OrderSubtotalLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        OrderSubtotalLabel.setText("###,###,###.##");

        javax.swing.GroupLayout NewOrderPanelLayout = new javax.swing.GroupLayout(NewOrderPanel);
        NewOrderPanel.setLayout(NewOrderPanelLayout);
        NewOrderPanelLayout.setHorizontalGroup(
            NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewOrderPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2)
                                .addComponent(CustSelectLabel)
                                .addGroup(NewOrderPanelLayout.createSequentialGroup()
                                    .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FirstNameLabel)
                                        .addGroup(NewOrderPanelLayout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(SearchForCustomerButton)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LastNameLabel)
                                        .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jSeparator1)
                                .addGroup(NewOrderPanelLayout.createSequentialGroup()
                                    .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CustFirstNameLabel)
                                        .addComponent(CustFirstName))
                                    .addGap(48, 48, 48)
                                    .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CustLastName)
                                        .addComponent(CustLastNameLabel)))
                                .addGroup(NewOrderPanelLayout.createSequentialGroup()
                                    .addComponent(EmailLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(CustEmail))
                                .addGroup(NewOrderPanelLayout.createSequentialGroup()
                                    .addComponent(PhoneLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(CustPhone))
                                .addGroup(NewOrderPanelLayout.createSequentialGroup()
                                    .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AddressLabel)
                                        .addGroup(NewOrderPanelLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(StreetLabel)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CustStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(NewOrderPanelLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(CityLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(CustCity)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(StateLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CustState)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ZipLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CustZip)))
                            .addComponent(CustInfoLabel))))
                .addGap(18, 18, 18)
                .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addGroup(NewOrderPanelLayout.createSequentialGroup()
                        .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrderItemsLabel)
                            .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NewOrderPanelLayout.createSequentialGroup()
                                    .addComponent(AddItemButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(EditItemButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DeleteItemButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SubtotalLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(OrderSubtotalLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(SubmitOrderButton))
                                .addComponent(ItemsScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        NewOrderPanelLayout.setVerticalGroup(
            NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustSelectLabel)
                    .addComponent(OrderItemsLabel))
                .addGap(3, 3, 3)
                .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewOrderPanelLayout.createSequentialGroup()
                        .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameLabel)
                            .addComponent(LastNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchForCustomerButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustInfoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustFirstNameLabel)
                            .addComponent(CustLastNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustFirstName)
                            .addComponent(CustLastName))
                        .addGap(9, 9, 9)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailLabel)
                            .addComponent(CustEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneLabel)
                            .addComponent(CustPhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(AddressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StreetLabel)
                            .addComponent(CustStreet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CityLabel)
                            .addComponent(CustCity)
                            .addComponent(StateLabel)
                            .addComponent(CustState)
                            .addComponent(ZipLabel)
                            .addComponent(CustZip)))
                    .addComponent(ItemsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddItemButton)
                    .addComponent(EditItemButton)
                    .addComponent(DeleteItemButton)
                    .addComponent(SubmitOrderButton)
                    .addComponent(SubtotalLabel)
                    .addComponent(OrderSubtotalLabel))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        OrdersTabbedPane.addTab("New Order", NewOrderPanel);

        AcitveOrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "OrderID", "CustomerID", "OrderDate", "OrderStatus", "TotalCost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ActiveOrdersScrollPane.setViewportView(AcitveOrdersTable);

        ApplyFiltersActiveButton.setText("Apply Filters...");

        ResetFiltersActiveButton.setText("Reset Filters");

        javax.swing.GroupLayout ActiveOrdersPanelLayout = new javax.swing.GroupLayout(ActiveOrdersPanel);
        ActiveOrdersPanel.setLayout(ActiveOrdersPanelLayout);
        ActiveOrdersPanelLayout.setHorizontalGroup(
            ActiveOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActiveOrdersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ActiveOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ActiveOrdersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ActiveOrdersPanelLayout.createSequentialGroup()
                        .addComponent(ApplyFiltersActiveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResetFiltersActiveButton)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        ActiveOrdersPanelLayout.setVerticalGroup(
            ActiveOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActiveOrdersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ActiveOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApplyFiltersActiveButton)
                    .addComponent(ResetFiltersActiveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActiveOrdersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        ActiveOrdersScrollPane.getAccessibleContext().setAccessibleName("");

        OrdersTabbedPane.addTab("Active Orders", ActiveOrdersPanel);

        ClosedOrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "OrderID", "CustomerID", "OrderDate", "DeliverDate", "TotalCost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ClosedOrdersScrollPane.setViewportView(ClosedOrdersTable);

        ApplyFiltersClosedButton.setText("Apply Filters...");

        ResetFiltersClosedButton.setText("Reset Filters");

        javax.swing.GroupLayout ClosedOrdersPanelLayout = new javax.swing.GroupLayout(ClosedOrdersPanel);
        ClosedOrdersPanel.setLayout(ClosedOrdersPanelLayout);
        ClosedOrdersPanelLayout.setHorizontalGroup(
            ClosedOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClosedOrdersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClosedOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClosedOrdersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ClosedOrdersPanelLayout.createSequentialGroup()
                        .addComponent(ApplyFiltersClosedButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResetFiltersClosedButton)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        ClosedOrdersPanelLayout.setVerticalGroup(
            ClosedOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClosedOrdersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClosedOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApplyFiltersClosedButton)
                    .addComponent(ResetFiltersClosedButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClosedOrdersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        OrdersTabbedPane.addTab("Closed Orders", ClosedOrdersPanel);

        NewCustomerButton.setText("New Customer");
        NewCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCustomerButtonActionPerformed(evt);
            }
        });

        EditCustomerButton.setText("Edit Selected");

        CustomersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CustomerID", "FirstName", "LastName", "Email", "Address", "Phone", "CustomerType", "LocationID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CustomerManagementScrollPane.setViewportView(CustomersTable);

        javax.swing.GroupLayout CustomerManagementPanelLayout = new javax.swing.GroupLayout(CustomerManagementPanel);
        CustomerManagementPanel.setLayout(CustomerManagementPanelLayout);
        CustomerManagementPanelLayout.setHorizontalGroup(
            CustomerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerManagementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomerManagementScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CustomerManagementPanelLayout.createSequentialGroup()
                        .addComponent(NewCustomerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditCustomerButton)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        CustomerManagementPanelLayout.setVerticalGroup(
            CustomerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerManagementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewCustomerButton)
                    .addComponent(EditCustomerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomerManagementScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        OrdersTabbedPane.addTab("Customer Management", CustomerManagementPanel);

        add(OrdersTabbedPane);
    }// </editor-fold>//GEN-END:initComponents

    private void NewCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCustomerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewCustomerButtonActionPerformed

    private void FirstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameFieldActionPerformed

    private void LastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameFieldActionPerformed

    private void DeleteItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteItemButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteItemButtonActionPerformed

    private void AddItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddItemButtonActionPerformed

    private void SubmitOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitOrderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitOrderButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AcitveOrdersTable;
    private javax.swing.JPanel ActiveOrdersPanel;
    private javax.swing.JScrollPane ActiveOrdersScrollPane;
    private javax.swing.JButton AddItemButton;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JButton ApplyFiltersActiveButton;
    private javax.swing.JButton ApplyFiltersClosedButton;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JPanel ClosedOrdersPanel;
    private javax.swing.JScrollPane ClosedOrdersScrollPane;
    private javax.swing.JTable ClosedOrdersTable;
    private javax.swing.JLabel CustCity;
    private javax.swing.JLabel CustEmail;
    private javax.swing.JLabel CustFirstName;
    private javax.swing.JLabel CustFirstNameLabel;
    private javax.swing.JLabel CustInfoLabel;
    private javax.swing.JLabel CustLastName;
    private javax.swing.JLabel CustLastNameLabel;
    private javax.swing.JLabel CustPhone;
    private javax.swing.JLabel CustSelectLabel;
    private javax.swing.JLabel CustState;
    private javax.swing.JLabel CustStreet;
    private javax.swing.JLabel CustZip;
    private javax.swing.JComboBox<String> CustomerComboBox;
    private javax.swing.JPanel CustomerManagementPanel;
    private javax.swing.JScrollPane CustomerManagementScrollPane;
    private javax.swing.JTable CustomersTable;
    private javax.swing.JButton DeleteItemButton;
    private javax.swing.JButton EditCustomerButton;
    private javax.swing.JButton EditItemButton;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JScrollPane ItemsScrollPane;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JButton NewCustomerButton;
    private javax.swing.JPanel NewOrderPanel;
    private javax.swing.JLabel OrderItemsLabel;
    private javax.swing.JTable OrderItemsTable;
    private javax.swing.JLabel OrderSubtotalLabel;
    private javax.swing.JTabbedPane OrdersTabbedPane;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JButton ResetFiltersActiveButton;
    private javax.swing.JButton ResetFiltersClosedButton;
    private javax.swing.JButton SearchForCustomerButton;
    private javax.swing.JLabel StateLabel;
    private javax.swing.JLabel StreetLabel;
    private javax.swing.JButton SubmitOrderButton;
    private javax.swing.JLabel SubtotalLabel;
    private javax.swing.JLabel ZipLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
