package view.inventorydb;

import view.orderdb.OrderPanel;
import control.DatabaseManager;

/**
 * The main Panel that represents a user selecting "Logistics" Dashboard from the Login
 * @author Paul Schmidt
 */
public class LogisticDashboard extends javax.swing.JPanel {
    /**
     * The dbm that holds a connection to the database
     */
    private DatabaseManager dbm;
    /**
     * Creates new form LogisticDashboard
     */
    public LogisticDashboard(final DatabaseManager dbm) {
        this.dbm = dbm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogisticsTabbedPanel = new javax.swing.JTabbedPane();
        InventoryPanel = new InventoryPanel(dbm);
        ActiveOrdersPanel = new OrderPanel("ACTIVE", dbm);
        ClosedOrdersPanel = new OrderPanel("CLOSED", dbm);
        VendorsPanel = new VendorPanel(dbm);

        setMinimumSize(new java.awt.Dimension(1280, 720));

        LogisticsTabbedPanel.addTab("Inventory", InventoryPanel);
        LogisticsTabbedPanel.addTab("Active Orders", ActiveOrdersPanel);
        LogisticsTabbedPanel.addTab("Closed Orders", ClosedOrdersPanel);
        LogisticsTabbedPanel.addTab("Vendors", VendorsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogisticsTabbedPanel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogisticsTabbedPanel)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.orderdb.OrderPanel ActiveOrdersPanel;
    private view.orderdb.OrderPanel ClosedOrdersPanel;
    private view.inventorydb.InventoryPanel InventoryPanel;
    private javax.swing.JTabbedPane LogisticsTabbedPanel;
    private view.inventorydb.VendorPanel VendorsPanel;
    // End of variables declaration//GEN-END:variables
}
